name = "chatter"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = "CHATTER_DATA"
bucket_name = "chatter-data"
